Remove some duplicates and run typo3-rector
slub/slub_events pull request #64
Opened 2021-03-19 14:21 UTC by PeaceSfiSh

I tried to remove some duplicated code blocks and fixed #63.

typo3-rector configuration

```
<?php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\PostRector\Rector\NameImportingPostRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Ssch\TYPO3Rector\Set\Typo3SetList;
use Ssch\TYPO3Rector\Configuration\Typo3Option;
use Ssch\TYPO3Rector\Rector\v9\v0\InjectAnnotationRector;

return static function (ContainerConfigurator $containerConfigurator): void {
    // get parameters
    $parameters = $containerConfigurator->parameters();

    // Define what rule sets will be applied
    $parameters->set(Option::SETS, [
        Typo3SetList::TYPO3_76,
        Typo3SetList::TYPO3_87,
        Typo3SetList::TYPO3_95
    ]);

    // FQN classes are not imported by default. If you don't do it manually after every Rector run, enable it by:
    $parameters->set(Option::AUTO_IMPORT_NAMES, true);

    // this will not import root namespace classes, like \DateTime or \Exception
    $parameters->set(Option::IMPORT_SHORT_CLASSES, false);

    // this will not import classes used in PHP DocBlocks, like in /** @var \Some\Class */
    $parameters->set(Option::IMPORT_DOC_BLOCKS, false);

    // Define your target version which you want to support
    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_72);

    // If you would like to see the changelog url when a rector is applied
    $parameters->set(Typo3Option::OUTPUT_CHANGELOG, true);

    // If you set option Option::AUTO_IMPORT_NAMES to true, you should consider excluding some TYPO3 files.
    $parameters->set(Option::SKIP, [
        NameImportingPostRector::class => [
            'ClassAliasMap.php',
            'ext_localconf.php',
            'ext_emconf.php',
            'ext_tables.php',
            __DIR__ . '/**/TCA/*',
            __DIR__ . '/**/Tests/*',
            __DIR__ . '/**/Configuration/RequestMiddlewares.php',
            __DIR__ . '/**/Configuration/Commands.php',
            __DIR__ . '/**/Configuration/AjaxRoutes.php',
            __DIR__ . '/**/Configuration/Extbase/Persistence/Classes.php',
        ],
        __DIR__ . '/**/Tests/*'
    ]);

    // If you have trouble that rector cannot run because some TYPO3 constants are not defined add an additional constants file
    // Have a look at https://github.com/sabbelasichon/typo3-rector/blob/master/typo3.constants.php
    // $parameters->set(Option::AUTOLOAD_PATHS, [
    //    __DIR__ . '/typo3.constants.php'
    // ]);

    // get services (needed for register a single rule)
    // $services = $containerConfigurator->services();

    // register a single rule
    // $services->set(InjectAnnotationRector::class);
};
```

2021-04-08 12:29 UTC, albig commented on Classes/Controller/LocationController.php
> +use TYPO3\CMS\Extbase\Mvc\Controller\ActionController;
Please put the use statement below the copyright notice.

2021-04-08 12:29 UTC, albig commented on Classes/Controller/SubscriberController.php
> +use TYPO3\CMS\Core\Page\PageRenderer;
Please put the use statement below the copyright notice.

2021-04-08 12:30 UTC, albig commented on Classes/Domain/Model/Category.php
> +use TYPO3\CMS\Extbase\DomainObject\AbstractEntity;
Please put the use statement below the copyright notice.

2021-04-08 12:30 UTC, albig commented on Classes/Domain/Model/Contact.php
> +use TYPO3\CMS\Extbase\DomainObject\AbstractEntity;
Please put the use statement below the copyright notice.

2021-04-08 12:30 UTC, albig commented on Classes/Domain/Model/Discipline.php
> +use TYPO3\CMS\Extbase\DomainObject\AbstractEntity;
Please put the use statement below the copyright notice.

2021-04-08 12:30 UTC, albig commented on Classes/Domain/Model/Event.php
> +use TYPO3\CMS\Extbase\DomainObject\AbstractEntity;
Please put the use statement below the copyright notice.

2021-04-08 12:31 UTC, albig commented on Classes/Domain/Repository/CategoryRepository.php
> +use TYPO3\CMS\Extbase\Persistence\Repository;
Please put the use statement below the copyright notice.

2021-04-08 12:31 UTC, albig commented on Classes/Domain/Repository/ContactRepository.php
> +use TYPO3\CMS\Extbase\Persistence\Repository;
Please put the use statement below the copyright notice.

2021-04-08 12:31 UTC, albig commented on Classes/Domain/Repository/DisciplineRepository.php
> +use TYPO3\CMS\Extbase\Persistence\Repository;
Please put the use statement below the copyright notice.

2021-04-08 12:31 UTC, albig commented on Classes/Domain/Repository/EventRepository.php
> +    use TYPO3\CMS\Extbase\Persistence\Repository;
Please put the use statement below the copyright notice.

2021-04-08 12:32 UTC, albig commented on Classes/Domain/Repository/LocationRepository.php
> +use TYPO3\CMS\Extbase\Persistence\Repository;
Please put the use statement below the copyright notice.

2021-04-08 12:32 UTC, albig commented on Classes/Domain/Repository/SubscriberRepository.php
> +use TYPO3\CMS\Extbase\Persistence\Repository;
Please put the use statement below the copyright notice.

2021-04-08 12:32 UTC, albig commented on Classes/Domain/Validator/SubscriberValidator.php
> +use TYPO3\CMS\Extbase\Validation\Validator\AbstractValidator;
Please put the use statement below the copyright notice.

2021-04-08 12:33 UTC, albig commented on Classes/Helper/Form/Element/RecurringEventsElement.php
> +use TYPO3\CMS\Core\Utility\GeneralUtility;
Please put the use statement below the copyright notice.

2021-04-08 12:33 UTC, albig commented on Classes/Slots/HookPostProcessing.php
> +use TYPO3\CMS\Extbase\Object\ObjectManager;
Please put the use statement below the copyright notice.

2021-04-08 12:34 UTC, albig commented on Classes/Task/CheckeventsTask.php
> +use TYPO3\CMS\Scheduler\Task\AbstractTask;
Please put the use statement below the copyright notice.

2021-04-08 12:34 UTC, albig commented on Classes/Task/CheckeventsTaskAdditionalFieldProvider.php
> +use TYPO3\CMS\Scheduler\Controller\SchedulerModuleController;
Please put the use statement below the copyright notice.

2021-04-08 12:34 UTC, albig commented on Classes/Task/CleanUpTask.php
> +use TYPO3\CMS\Scheduler\Task\AbstractTask;
Please put the use statement below the copyright notice.

2021-04-08 12:34 UTC, albig commented on Classes/Task/CleanUpTaskAdditionalFieldProvider.php
> +use TYPO3\CMS\Scheduler\Controller\SchedulerModuleController;
Please put the use statement below the copyright notice.

2021-04-08 12:34 UTC, albig commented on Classes/Task/StatisticsTask.php
> +use TYPO3\CMS\Scheduler\Task\AbstractTask;
Please put the use statement below the copyright notice.

2021-04-08 12:35 UTC, albig commented on Classes/ViewHelpers/Be/FunctionBarViewHelper.php
> +use TYPO3\CMS\Fluid\ViewHelpers\Be\AbstractBackendViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:35 UTC, albig commented on Classes/ViewHelpers/Condition/GbEventsOfCategoryViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:35 UTC, albig commented on Classes/ViewHelpers/Condition/InArrayViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Condition/IsPastEventViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Condition/IsSubscriptionAllowedViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Format/BookedPlacesViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Format/CsvEscapeViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Format/DateDiffViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Format/EditCodeViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Format/EventsOfCategoryViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Format/EventsOfDisciplineViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:36 UTC, albig commented on Classes/ViewHelpers/Format/FreePlacesLeftViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:37 UTC, albig commented on Classes/ViewHelpers/Format/Fullcalendar/JsFooterViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:37 UTC, albig commented on Classes/ViewHelpers/Format/NewMonthTitleViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:37 UTC, albig commented on Classes/ViewHelpers/Format/OneLineViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:37 UTC, albig commented on Classes/ViewHelpers/Format/TrimViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:37 UTC, albig commented on Classes/ViewHelpers/Link/Is3dModelViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:37 UTC, albig commented on Classes/ViewHelpers/Link/IslocalViewHelper.php
> +use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
Please put the use statement below the copyright notice.

2021-04-08 12:53 UTC, albig requested changes
Thank you for your work and sorry for the late reply.

Everything seems to work as expected.

Just a wish to make the formating constistently. I was used with TYPO3 9 to have the namespace above and the use statements below the copyright notice. I've seen, this has changed with TYPO3 10. Everything is now _below_ the copyright notice. This seems to be kept in TYPO3 11.

So, I would suggest, to make it consistently like TYPO3 10+.

I'm a little confused about Helper and Utility directory. Do we really need both? The "helper" are some helping utilities ;-) But that's not so important. I think, I understand your distinction.

2021-05-31 13:33 UTC, albig commented
I don't know, if this makes a difference with rector. But we need no support of TYPO3 7.6 in this pull request anymore.

2021-05-31 13:49 UTC, PeaceSfiSh commented
The ruleset definition from 7 to 9 is like a transition from v6-compatibility to v9-compatibility.
e.g. Typo3SetList::TYPO3_76 includes the rules for the migration from 6 LTS to 7 LTS
all three rulesets end in a better v9 LTS compatibility by removing old TCA-options or migrating them

2021-06-07 15:03 UTC, merged